enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended-anddea]
app-name = "YT RVX anddea"
enabled = true
build-mode = "module"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
#rv-brand = "ReVanced Extended anddea"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
module-prop-name = "yt-rvx-anddea"
arch = "all"
riplib = true


[YouTube-Music-Extended-anddea]
app-name = "YT-Music RVX anddea"
enabled = true
build-mode = "module"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
#rv-brand = "ReVanced Extended anddea"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx-anddea"
arch = "both"
riplib = true


[YouTube-Morphe]
app-name = "YT Morphe"
enabled = true
build-mode = "module"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
#rv-brand = "Morphe"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
module-prop-name = "yt-morphe"
arch = "all"
riplib = true


[YouTube-Music-Morphe]
app-name = "YT-Music Morphe"
enabled = true
build-mode = "module"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
#rv-brand = "Morphe"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-morphe"
arch = "both"
riplib = true


[Reddit-Morphe]
app-name = "Reddit Morphe"
enabled = true
build-mode = "module"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
#rv-brand = "Morphe"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
module-prop-name = "reddit-morphe"
arch = "all"
riplib = true
